apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CHANGE_CLUSTER_NAME
  region: CHANGE_REGION

nodeGroups:
  - name: hub
    instanceType: m5.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 100
    volumeType: gp2
    ssh:
        publicKeyPath: CHANGE_PUBLICKEY
    ami: auto
    amiFamily: AmazonLinux2
  - name: user-notebook
    instanceType: m5.2xlarge
    minSize: 0
    maxSize: 20
    desiredCapacity: 0
    volumeSize: 100
    volumeType: gp2
    ssh:
        publicKeyPath: CHANGE_PUBLICKEY
    ami: auto
    amiFamily: AmazonLinux2
    iam:
      withAddonPolicies:
          autoScaler: true
          efs: true
  - name: dask-worker
    instanceType: r5.2xlarge
    minSize: 0
    maxSize: 20
    volumeSize: 100
    volumeType: gp2
    desiredCapacity: 0
    ssh:
        publicKeyPath: CHANGE_PUBLICKEY
    ami: auto
    amiFamily: AmazonLinux2
    iam:
      withAddonPolicies:
          autoScaler: true
          efs: true
